icons: icon-files と組み合わせて動くようにする + Loader 周りをリファクタリング
pixiv/charcoal pull request #149
Opened 2022-11-14 15:14 UTC by fsubal

## やったこと

- `charcoal-ui/icons` が `charcoal-ui/icon-files` と組み合わせて動くようにする
  - これまで loader は UrlLoader だけでほぼ全部やっていたが、icon-files に収録されているやつとそれ以外で別の loader クラスを使うようにする
- loader の登録（ addCustomIcon ）と解決（ getIcon ）周りをリファクタ
- loader.ts を複数ファイルに分ける
- せっかくなので ARCHITECTURE.md を書く

## 動作確認環境

Storybook。とりあえず webpack 版と vite 版で動いてそうなのを確認

## チェックリスト

不要なチェック項目は消して構いません

- [ ] 破壊的変更がある場合には、対象のパッケージのメジャーバージョンが上がっていることを確認した
- [x] 追加したコンポーネントが index.ts から再 export されている
- [x] README やドキュメントに影響があることを確認した

プロジェクトのバンドラをどう設定すればいいか、は別途 @mimokmt に変えてもらう予定なのでいったん放置

2022-11-14 23:45 UTC, fsubal commented on packages/icons/package.json
> +    "@charcoal-ui/icon-files": "workspace:^",
これバージョン指定で入れたいので、先に icon-files を publish したほうが良さそう

2022-11-24 02:23 UTC, ciffelia requested changes

2022-11-24 02:23 UTC, ciffelia commented on packages/icons/src/loaders/CharcoalIconFilesLoader.ts
> +        throw new PixivIconLoadError(this._name)
デバッグのしやすさを考えると`importIconFile`が投げたエラーが具体的に何だったのかわかるようにしておくのが良さそうです。

単にコンソールに出力するか、

```suggestion
      .catch((e) => {
        console.error(e)
        throw new PixivIconLoadError(this._name)
```

あるいは`PixivIconLoadError`のコンストラクタに`Error`を渡せるようにして、具体的なエラーの情報をmessageに含めるのはどうでしょうか

```ts
export class PixivIconLoadError extends Error {
  constructor(name: string, causedBy?: { toString(): string }) {
    super(`Failed to fetch <pixiv-icon name="${name}">${causedBy === undefined ? '' : `: ${causedBy}`}`)
    Object.setPrototypeOf(this, new.target)
  }
}
```

```suggestion
      .catch((e) => {
        throw new PixivIconLoadError(this._name, e)
```

2022-11-24 02:23 UTC, ciffelia commented on packages/icons/src/loaders/CustomIconLoader.ts
> +    this._promise = fetch(this._filePathOrUrl)
fetchがrejectしたときに`PixivIconLoadError`ではなくfetchのエラーがそのまま出ますが、これは意図的ですか？

2022-11-24 02:31 UTC, fsubal commented on packages/icons/src/loaders/CharcoalIconFilesLoader.ts
> +        throw new PixivIconLoadError(this._name)
ES2022 だと `Error.prototype.cause` があるので理想的にはそっちに乗るほうが良さそうなんですよね。

https://zenn.dev/petamoriken/articles/bb123b2f50cdab

polyfill 入れないとつらい感じになるとかなら挙げてもらった方法にしてもいいですが

2022-11-24 02:34 UTC, fsubal commented on packages/icons/src/loaders/CustomIconLoader.ts
> +    this._promise = fetch(this._filePathOrUrl)
見落としていた。直したほうが良いです

2022-11-24 08:26 UTC, fsubal commented on packages/icons/src/loaders/CustomIconLoader.ts
> +    this._promise = fetch(this._filePathOrUrl)
ここでハンドルしてもいいし、`getIcon` が最終的に全部 catch して `PixivIconLoadError` にするというのもアリだな

2022-11-28 06:24 UTC, fsubal commented on packages/icons/src/loaders/PixivIconLoadError.ts
> +    }
これは cause に文字列を渡すと `""` で勝手に囲まれるということがおきますが、まぁ許容してます（ Error オブジェクト以外はよくわからないので toString しない考え ）

2022-11-28 06:28 UTC, fsubal commented
え、通らないのか（ tsconfig ? ）

```
➤ YN0000: [@charcoal-ui/icons]: src/loaders/PixivIconLoadError.ts(10,20): error TS2554: Expected 0-1 arguments, but got 2.
```

2022-11-28 09:34 UTC, fsubal commented
どうやら lib に es2022 が入るのが TS 4.6+ っぽい？つまり TypeScript をアプデしないと Error Cause は使えない。一旦なしにしよう

2022-12-01 07:22 UTC, ciffelia approved these changes
`Error.prototype.cause`は初耳でした。TSのアップデート後に`{ cause }`を渡すようにするとのことでLGTMです。

2022-12-02 06:48 UTC, merged