feat(react): Implement `<Select />`/`SelectGroup />` components
pixiv/charcoal pull request #43
Opened 2022-04-20 10:53 UTC by mkobayashime

## やったこと

- 

## 動作確認環境

## チェックリスト

不要なチェック項目は消して構いません

- [ ] 破壊的変更がある場合には、対象のパッケージのメジャーバージョンが上がっていることを確認した
- [ ] 追加したコンポーネントが index.ts から再 export されている

2022-04-21 01:23 UTC, mkobayashime commented on packages/react/src/components/Select/index.tsx
> +      <SelectInputOverlay overlay={overlay} aria-hidden={true}>
`overlay` 時の白ボーダーとチェックマークを `position: absolute` で配置したいが、`input` の中に入れるわけにはいかないので `aria-hidden='true'` のダミー `div` を用意する

2022-04-21 01:29 UTC, fsubal commented on packages/react/src/components/Select/index.tsx
> +        <pixiv-icon name="24/Check" unsafe-non-guideline-scale={16 / 24} />
そういえば charcoal-ui/react 内で pixiv-icon を使う場合、`import '@charcoal-ui/pixiv-icon'` はどこに書かれると良いんだろう（書かないと Custom Elements が登録されない）

2022-04-21 01:36 UTC, fsubal commented on packages/react/src/components/Select/index.tsx
> +        <pixiv-icon name="24/Check" unsafe-non-guideline-scale={16 / 24} />
おそらく `@charcoal-ui/react` が `<Icon>` コンポーネントを持ち、その中で import すると良い。
ただし今 `import '@charcoal-ui/pixiv-icon'` は SSR 時に呼ばれることを想定してないのでそっちも直す必要がある。

この PR 内ではそこまでやらなくて良い。

2022-04-21 01:43 UTC, pnlybubbles requested changes

2022-04-21 01:43 UTC, pnlybubbles commented on packages/react/src/components/Select/index.tsx
> +  overlay?: boolean
[IMO] こんごvariantが増えたケースに対応できるように、`variant: 'default' | 'overlay'` とかにするのはありかも

2022-04-21 01:43 UTC, pnlybubbles commented on packages/react/src/components/Select/index.tsx
> +const SelectRoot = styled.label<{ disabled: boolean }>`
[SHOULD] disabledとaria-disabledと重複している点, disabledの分岐でjsでの処理を必要としている点を考慮すると、 styledのpropsで受け取らないほうがよいかな。`disabledSelector`を使うようにしよう。

https://github.com/pixiv/charcoal/blob/59790fe65d62df8142ebaaca7e874a44875c82f9/packages/react/src/components/Clickable/index.tsx#L53-L55

2022-04-21 01:45 UTC, fsubal commented on packages/react/src/components/Select/index.story.tsx
> +  title: Select.name,
関数名って production build だと minify されて、結果ここも minify された名前になったりしないっけ（ Storybook のビルド時の minify がどういう設定かは知らないが ）

2022-04-21 02:07 UTC, fsubal commented on packages/react/src/components/Select/index.tsx
> +  grid-gap: ${({ theme }) => px(theme.spacing[8])};
gap で良い

2022-04-21 02:15 UTC, pnlybubbles commented on packages/react/src/components/Select/index.tsx
> +      theme((o) => [o.borderRadius('oval'), hasError && o.outline.assertive])};
[MUST] theme呼び出しを1回にしたい！(現状の制約でhover transitionが効かなくなるケースがある)

2022-04-21 02:16 UTC, pnlybubbles commented on packages/react/src/components/Select/index.tsx
> +  color: ${({ theme }) => theme.color.text5};
color も themeで実現できそう

2022-04-21 02:17 UTC, pnlybubbles commented on packages/react/src/components/Select/index.tsx
> +  variant = 'default',
OK!

2022-04-21 02:18 UTC, pnlybubbles reviewed
操作可能な story も追加したい (storyにコンポーネントを作ってuseStateをしよう)

2022-04-21 06:41 UTC, pnlybubbles approved these changes
LGTM

2022-04-21 06:41 UTC, pnlybubbles commented on packages/react/src/components/Select/index.test.tsx
> +      expect(parent.getAttribute('aria-label')).toBe('defaultAriaLabel')
👍

2022-04-21 06:41 UTC, pnlybubbles commented on packages/react/src/components/Select/index.test.tsx
> +    it('all the options have `aria-invalid="true"`', () => {
👍

2022-04-21 08:46 UTC, fsubal approved these changes

2022-04-22 01:22 UTC, merged

2022-04-22 01:24 UTC, pnlybubbles commented
resolve #42